add error handling for Drush command in install step

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -52,4 +52,8 @@ runs:
       run: |
         set -e
         ddev composer install
-        ddev install-site
+        ddev install-site 2>&1 | tee output.log
+        if grep -q 'Warning: Drush command terminated abnormally.' output.log; then
+          echo "Error: Drush command terminated abnormally."
+          exit 1
+        fi
